version: "3.8"

services:
  app:
    image: mcr.microsoft.com/devcontainers/javascript-node:22-bookworm
    container_name: wedding-invite-app
    volumes:
      - ..:/workspace:cached

    command: sleep infinity

    # Указываем Docker Compose читать переменные из файла
    env_file:
      - ../.env.local

    ports:
      - "3000:3000"
      - "4983:4983"

    depends_on:
      - db

    user: node

  db:
    image: postgres:16-alpine
    container_name: wedding-invite-db
    restart: unless-stopped

    # Базе тоже нужны эти переменные (POSTGRES_USER и т.д.)
    env_file:
      - ../.env.local

    volumes:
      - wedding-db-data:/var/lib/postgresql/data

volumes:
  wedding-db-data:
